# Site settings
title: Blog 3.0
description: Finally working
baseurl: "/blog3.0/" # the subpath of your site, e.g. /blog
url: "https://tbarasch.github.io/blog3.0/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tani Barasch
user_description: Student
user_title: Student
email: baraschmr@gmail.com
twitter: non exsistent

github_username:  tbarasch


exclude: ['package.json', 'src' , 'node_modules']
